export const ACTION_TYPES = {
    API_CREATE_ORDER: 'ORDER/API_CREATE_ORDER',
    API_GET_ALL_HISTORY_ORDER_OF_USER: 'ORDER/API_GET_ALL_HISTORY_ORDER_OF_USER',
    API_GET_DETAIL_ORDER_BY_ID: 'ORDER/API_GET_DETAIL_ORDER_BY_ID',
    API_CANCEL_ORDER: 'ORDER/API_CANCEL_ORDER'
}