export const ACTION_TYPES = {
    API_LOGIN: 'AUTH/LOGIN',
    API_FORGET_PASSWORD: 'AUTH/API_FORGET_PASSWORD',
    API_GET_INFO_USER: 'AUTH/API_GET_INFO_USER',
    API_REGISTER: 'AUTH/API_REGISTER',
    API_UPDATE_INFO: 'AUTH/API_UPDATE_INFO',
    API_UPDATE_PASSWORD: 'AUTH/API_UPDATE_PASSWORD',
}