export const ACTION_TYPES = {
    API_GET_ALL_DISTRICT: 'ADDRESS/API_GET_ALL_DISTRICT',
    API_GET_WARD_BY_DISTRICT: 'ADDRESS/API_GET_WARD_BY_DISTRICT',
    SET_MY_ADDRESS: 'ADDRESS/SET_MY_ADDRESS',
}