export const ACTION_TYPES = {
    API_GET_CATEGORIES: 'LIST/API_GET_CATEGORIES',
    API_GET_RESTAURENTS_BY_NEAR_ME: 'LIST/API_GET_RESTAURENTS_BY_NEAR_ME',
    GEOLOCATION: 'LIST/GEOLOCATION',

    API_GET_MENU_RES: 'LIST/API_GET_MENU_RES',
    API_GET_RESTAURANT_BY_CATEGORY: 'LIST/API_GET_RESTAURANT_BY_CATEGORY',
    API_GET_RESTAURANT_BY_PAGE: 'LIST/API_GET_RESTAURANT_BY_PAGE',
    API_SEARCH_RESTAURANT_BY_NAME: 'LIST/API_SEARCH_RESTAURANT_BY_NAME',
    CURRENT_RESTAURANT: 'CURRENT_RESTAURANT',
}